# Generated by Django 2.1.7 on 2019-03-28 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alter_Jeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('popularite', models.PositiveSmallIntegerField()),
                ('date_creation', models.DateField()),
                ('version', models.PositiveSmallIntegerField()),
                ('picture_in_game_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Createur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SC', 'Scenariste'), ('GD', 'Game Designer'), ('TE', 'Testeur'), ('GR', 'Graphiste'), ('CR', 'Créateur'), ('AR', 'Artisan')], default='Créateur', max_length=15)),
                ('auteur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_jeu', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('popularite', models.PositiveSmallIntegerField()),
                ('date_creation', models.DateField()),
                ('version', models.PositiveSmallIntegerField()),
                ('picture_url', models.CharField(max_length=255)),
                ('picture_in_game_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('PI', 'Pion'), ('PL', 'Plateau'), ('CA', 'Carte'), ('TO', 'Totem'), ('DE', 'Dé'), ('SA', 'Sablier'), ('AU', 'Autre')], default='Autre', max_length=8)),
                ('description', models.TextField()),
                ('previsualisation', models.TextField()),
                ('url_telechargement', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Piece_jeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeux.Jeu')),
                ('piece_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeux.Piece')),
            ],
        ),
        migrations.CreateModel(
            name='Regle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiels', models.TextField()),
                ('tour_de_jeu', models.TextField()),
                ('annexes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='jeu',
            name='regle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeux.Regle'),
        ),
        migrations.AddField(
            model_name='createur',
            name='jeu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeux.Jeu'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete=models.SET('Commentaire effacé'), to='jeux.Createur'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='jeu_id',
            field=models.ForeignKey(on_delete=models.SET('Commentaire effacé'), to='jeux.Jeu'),
        ),
        migrations.AddField(
            model_name='alter_jeu',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeux.Jeu'),
        ),
        migrations.AddField(
            model_name='alter_jeu',
            name='regle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeux.Regle'),
        ),
    ]
