# Generated by Django 2.1.7 on 2019-03-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jeu',
            options={'verbose_name_plural': 'jeux'},
        ),
    ]
